version: '3.8'

services:
  mongodb:
    networks:
      - jupyter-mongo-net
    image: mongo:4.4
    container_name: mongodb-container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb_data:/data/db
      - ./config/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
    # logging:
    #   driver: gelf
    #   options:
    #     gelf-address: "udp://localhost:12201"
    #     tag: "mongodb-log"
    # shm_size: 25g
networks:
  jupyter-mongo-net:
    external: true
volumes:
  mongodb_data: