version: '3'

services:
  jupyter:
    networks:
      - jupyter-mongo-net
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    command: start-notebook.sh --NotebookApp.token=''
networks:
  jupyter-mongo-net:
    external: true